// Artifact library — outputs completed agent tasks have produced.
// Novartis Oncology fill — sized around the ASCO/ESMO 2025 cycle and
// the Veeva Medical_Insight loop framing.

export const ARTIFACTS = [
  {
    id: 'ART1',
    title: 'Strategy-to-Action — ASCO/ESMO 2025 cycle',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2025-10-28',
    summary: 'Full Strategy-to-Action: 4 ISP pillars, 5 MO coverage, 7 prioritised insights, 14 proposed/in-flight actions, Gap Radar suggestions including the cross-tumour Medical Affairs platform LP.',
    dataSources: ['Veeva CRM Medical_Insight', 'Capture App field signal', 'Ad board transcripts', 'Congress capture (ASCO + ESMO 2025)'],
    sizeLabel: '3.1 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART2',
    title: 'ASCO 2025 Debrief — Kisqali, Pluvicto & Scemblix readouts',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2025-06-08',
    summary: 'Synthesised read on NATALEE 4-yr iDFS, PSMAfore pre-taxane data, and ASC4FIRST 1L CML — including competitor visibility and recommended MSL talk-track shifts.',
    dataSources: ['ASCO 2025 abstracts', 'Plenary session capture', 'Social backchannels', 'Veeva CRM Medical_Insight'],
    sizeLabel: '2.4 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART3',
    title: 'Cross-Tumour KOL Map — Phase 1 / Drug Development network',
    type: 'interactive',
    agent: 'LUCA',
    taskType: 'KOL Selection & Profiling',
    dateCreated: '2025-10-22',
    summary: 'Live KOL map highlighting cross-tumour influencers (Lillian Siu cluster) — KOLs surfacing in Kisqali, Pluvicto and Scemblix Veeva insight streams in the same cycle. Re-tier candidates flagged.',
    dataSources: ['Veeva CRM Medical_Insight', 'PubMed', 'ASCO/ESMO speaker programs', 'Trial PI registries'],
    sizeLabel: 'In-app',
    provenance: 'synthesized',
  },
  {
    id: 'ART4',
    title: 'Adjuvant Kisqali Workflow Algorithm v1 — community-oncology leave-behind',
    type: 'pptx',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2025-09-30',
    summary: 'Co-created with community-oncology MSL field input. QTc monitoring + dose-modification algorithm. Deployed to 184 community centres post-NATALEE 4-yr update. AI1 → A1 lineage.',
    dataSources: ['Veeva CRM Medical_Insight', 'Ad board transcripts', 'NATALEE long-term data'],
    sizeLabel: '4.6 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART5',
    title: 'Theranostic Centre Activation Program — site-readiness checklist',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Evidence Generation',
    dateCreated: '2025-10-15',
    summary: 'Operational playbook for new theranostic centres: radiation safety, scheduling workflow, isotope supply, billing, MSL talking points. 23 sites onboarded; wait-list reduced from 9.2 to 5.1 weeks. AI4 → A7 lineage.',
    dataSources: ['Veeva CRM Medical_Insight', 'Site-of-care field surveys', 'Internal operations', 'Reimbursement landscape'],
    sizeLabel: '5.4 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART6',
    title: 'ASCO → ESMO 2025 Sentiment Trend — Pluvicto positioning',
    type: 'interactive',
    agent: 'ARIA',
    taskType: 'Congress Intelligence',
    dateCreated: '2025-10-26',
    summary: 'Cycle-over-cycle sentiment shift on Pluvicto sequencing. Tracks the "foundation, not endpoint" narrative emergence as 225Ac-PSMA pipeline gained ESMO 2025 platform exposure.',
    dataSources: ['ASCO 2025 abstracts', 'ESMO 2025 abstracts', 'Social commentary', 'Veeva CRM Medical_Insight'],
    sizeLabel: 'In-app',
    provenance: 'synthesized',
  },
];
