// Actionable Insights — Novartis Oncology Medical Affairs.
// Tied to the strategy framework (MO1..MO5 / LP1..LP6) defined in
// strategy.js. Source insights flag the Veeva Medical_Insight provenance
// per Thiru's brief — the demo's core "field-to-strategy loop" story.

export const INSIGHTS = [
  {
    id: 'AI1',
    title: 'Adjuvant Kisqali narrative still gated by community-oncology tolerability story',
    priority: 'High',
    lpRefs: ['LP1'], moRefs: ['MO1'],
    recurrence: 4,
    recency: '2025-10',
    summary: 'Community medical oncologists post-NATALEE 4-yr update want the iDFS narrative but are anchoring on QTc monitoring and transaminase elevation as workflow blockers. The science has landed; the operational story has not.',
    sourceInsights: [
      { type: 'Veeva Medical_Insight', role: 'Community medical oncologist', location: 'Atlanta, GA',     quote: 'I believe in the iDFS data — I just need a one-page workflow for the QTc monitoring and a clean dose-modification algorithm.', date: '2025-10-04' },
      { type: 'Ad board',              role: 'Academic medical oncologist', location: 'Boston, MA',      quote: 'My colleagues in the community are stuck on logistics. Bring them an algorithm, not another slide deck.',                          date: '2025-09-22' },
      { type: 'Congress capture',      role: 'Tier 2 KOL',                  location: 'ASCO 2025 — Chicago', quote: 'Adjuvant uptake is rate-limited by what oncologists can operationalise — not what the trial showed.',                            date: '2025-06-02' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.91,
    provenance: 'Veeva Medical_Insight + ASCO capture',
  },
  {
    id: 'AI2',
    title: 'CDK4/6 sequencing decision — Kisqali OS magnitude not breaking through',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 5,
    recency: '2025-09',
    summary: 'Community 1L mBC decisions cluster on institutional habit rather than head-to-head OS data. Kisqali OS magnitude is being undersold in MSL conversations relative to Verzenio adjuvant breadth.',
    sourceInsights: [
      { type: 'Veeva Medical_Insight', role: 'MSL field report',  location: 'Phoenix, AZ',           quote: '7 of 11 1L mBC decisions in Q3 went to whatever the institution had on protocol — not based on OS.',                       date: '2025-09-18' },
      { type: 'Ad board',              role: 'Tier 1 breast KOL', location: 'San Francisco, CA',     quote: 'The OS magnitude story is only landing where MSLs are explicitly running it — we need a head-to-head leave-behind.',          date: '2025-09-01' },
      { type: 'Med Info query',        role: 'Community oncologist', location: 'Tampa, FL',          quote: 'Asked for a Kisqali vs Verzenio comparison card — clinical not promotional.',                                              date: '2025-09-25' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.88,
    provenance: 'Veeva Medical_Insight cluster',
  },
  {
    id: 'AI3',
    title: 'Pluvicto pre-taxane sequencing — urology vs medical oncology disagreement',
    priority: 'High',
    lpRefs: ['LP3'], moRefs: ['MO3'],
    recurrence: 4,
    recency: '2025-10',
    summary: 'Post-PSMAfore, urologists are advocating earlier Pluvicto referral while medical oncology splits on whether ARPI-pretreated patients should go to RLT before docetaxel. The referral pathway is contested.',
    sourceInsights: [
      { type: 'Veeva Medical_Insight', role: 'Urologist',                   location: 'Charleston, SC',  quote: 'Why are we waiting for chemo failure when PSMAfore showed pre-taxane benefit? My referral threshold is dropping.',  date: '2025-10-12' },
      { type: 'Veeva Medical_Insight', role: 'Medical oncologist',          location: 'Boston, MA',       quote: 'Sequencing depends on disease tempo — slow biochemical recurrence vs visceral disease. PSMAfore doesn\'t answer that.', date: '2025-10-08' },
      { type: 'Congress capture',      role: 'Tier 1 GU KOL',               location: 'ASCO 2025 — Chicago', quote: 'PSMAfore reframes the conversation but the algorithm hasn\'t caught up.',                                       date: '2025-06-03' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.86,
    provenance: 'Veeva Medical_Insight + ASCO capture',
  },
  {
    id: 'AI4',
    title: 'PSMA-RLT site-of-care capacity is the limiting reagent',
    priority: 'High',
    lpRefs: ['LP4'], moRefs: ['MO3'],
    recurrence: 6,
    recency: '2025-10',
    summary: 'Theranostic centre wait lists of 6–12 weeks are now the dominant Pluvicto access barrier — not payer access or imaging. The narrative is shifting from "convince oncologists" to "scale the operational footprint."',
    sourceInsights: [
      { type: 'Veeva Medical_Insight', role: 'MSL field report',     location: 'Cleveland, OH',         quote: 'Three centres in my territory have 8+ week wait lists. Patients are progressing while waiting — referrers are pulling back.', date: '2025-10-22' },
      { type: 'Ad board',              role: 'Theranostic radiologist', location: 'New York, NY',       quote: 'We can credential more centres but we can\'t scale isotope supply chain in a quarter. This is a 12-month problem.',          date: '2025-09-18' },
      { type: 'Med Info query',        role: 'Hospital pharmacy',    location: 'Dallas, TX',            quote: 'How does Novartis support new theranostic centre standup? We have the demand but not the experience.',                  date: '2025-10-30' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.93,
    provenance: 'Veeva Medical_Insight cluster',
  },
  {
    id: 'AI5',
    title: 'ASC4FIRST 1L Scemblix uptake — community sites blocked on cost-effectiveness',
    priority: 'Medium',
    lpRefs: ['LP5'], moRefs: ['MO4'],
    recurrence: 3,
    recency: '2025-09',
    summary: 'Academic CML treaters are aligned on Scemblix as 1L preference post-ASC4FIRST. Community sites and value-based care contracts are stuck without a credible pharmacoeconomic story vs generic imatinib.',
    sourceInsights: [
      { type: 'Veeva Medical_Insight', role: 'Community heme/onc',     location: 'Albany, NY',           quote: 'I want to use it 1L but our institution\'s value committee asked for a cost-per-MMR analysis I don\'t have.',         date: '2025-09-04' },
      { type: 'Ad board',              role: 'Academic CML KOL',        location: 'Augusta, GA',          quote: 'The clinical case is closed — the pharmacoeconomic case is what blocks 1L uptake in non-academic settings.',          date: '2025-08-28' },
      { type: 'Congress capture',       role: 'Tier 1 heme KOL',        location: 'EHA 2025 — Milan',     quote: 'European centres are watching what the U.S. does with cost-effectiveness — it\'ll set the global tone.',             date: '2025-06-13' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.84,
    provenance: 'Veeva Medical_Insight + EHA capture',
  },
  {
    id: 'AI6',
    title: '225Ac-PSMA programs reframing Pluvicto as "foundation, not endpoint"',
    priority: 'High',
    lpRefs: ['LP3'], moRefs: ['MO3'],
    recurrence: 3,
    recency: '2025-10',
    summary: 'Multiple ESMO 2025 platform sessions on 225Ac-PSMA pipelines have shifted KOL framing. Pluvicto positioning needs to evolve from "the PSMA RLT" to "the PSMA RLT foundation that enables next-gen sequencing".',
    sourceInsights: [
      { type: 'Congress capture',     role: 'Tier 1 GU KOL', location: 'ESMO 2025 — Berlin', quote: 'The question isn\'t whether 225Ac-PSMA works — it\'s how we sequence it after lutetium.',                                date: '2025-10-19' },
      { type: 'Veeva Medical_Insight', role: 'Medical oncologist',  location: 'Houston, TX',         quote: 'Patients who responded to Pluvicto and progressed are the obvious 225Ac trial candidates. We need that pathway clear.',  date: '2025-10-25' },
      { type: 'Social signal',         role: 'Backchannel discussion', location: 'ESMO 2025 — Berlin', quote: 'No one\'s arguing Pluvicto is yesterday\'s news — but no one\'s arguing it\'s tomorrow\'s either.',               date: '2025-10-20' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.79,
    provenance: 'ESMO capture + Veeva Medical_Insight',
  },
  {
    id: 'AI7',
    title: 'Cross-tumour KOLs underused — drug-development network is strategic blind spot',
    priority: 'Medium',
    lpRefs: ['LP6'], moRefs: ['MO5'],
    recurrence: 2,
    recency: '2025-10',
    summary: 'KOLs who span breast, prostate and heme (Phase 1 / drug-development network) are underrepresented in Veeva engagement plans. They drive platform-level decisions but Medical Affairs reporting is asset-by-asset.',
    sourceInsights: [
      { type: 'Veeva Medical_Insight', role: 'MSL — drug development network', location: 'Toronto, CA', quote: 'Lillian Siu\'s network sees Pluvicto, Kisqali and Scemblix in the same conversation — but our CRM treats them as three separate engagements.', date: '2025-10-15' },
      { type: 'Ad board',              role: 'Tier 1 cross-tumour KOL', location: 'Toronto, CA',         quote: 'When you talk to me about Pluvicto only, you\'re missing 60% of what I see across tumour types.',                                              date: '2025-10-02' },
    ],
    status: 'Validated',
    confidenceScore: 0.74,
    provenance: 'Veeva Medical_Insight',
  },
];
